version: '3.8'
services:
  php:
    build:
      dockerfile: Dockerfile
    container_name: php-app
    volumes:
      - ./public:/var/www/html
      - ./app:/var/www/html/app
      - ./config:/var/www/html/config
      - ./scripts:/var/www/html/scripts
    ports:
      - "8000:80"
    environment:
      - PRECIO_USD=${PRECIO_USD}
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge_db
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts:/docker-entrypoint-initdb.d

volumes:
  db_data:
